### ISSUE TITLE
Need somebody to take over this project

### ISSUE THREAD

**Issue by mikelawrence** [mikelawrence/senseme-hacs#35]
Divorce makes things a real PITA.

Anybody interested in assuming the responsibility for this project and aiosenseme let me know.

@bdraco maybe?

**Comment by bdraco** [comment]
I can take it over as long as you are fine with merging it to core (just the actual integration part)

If you open the initial PR to show consent I can take care of getting it ready for merge.

**Comment by bdraco** [comment]
😢 divorce is never fun. Hope it gets better for you soon!

**Comment by bkvargyas** [comment]
I see there hasn't been any movement on this.

I'm in favor of merging this solution into core and letting @bdraco take this process over.   

I now have over 18 Haiku fans being controlled with this integration across 3 properties and rely on this integration working everyday.   I very much appreciate all the effort and time @mikelawrence has put into this over time to make this a reality and help push home assistant forward, I have no coding experience, otherwise I would assist.

Brian

**Comment by OzGav** [comment]
Hopefully this isn't a Mary Celeste. I have just submitted a small PR to fix a warning in 2021.12 https://github.com/mikelawrence/senseme-hacs/pull/38

**Comment by mikelawrence** [comment]
So I have some time next week to work on merging this with the HA Core. @bdraco are you still up for completing the merge request once I give consent?

**Comment by mikelawrence** [comment]
@OzGav and @bkvargyas Hopefully there will be some movement on this soon.

**Comment by bdraco** [comment]
> So I have some time next week to work on merging this with the HA Core. @bdraco are you still up for completing the merge request once I give consent?

Yes.  As soon as the PR is open and the CLA is done, I can finish the rest.

**Comment by mikelawrence** [comment]
I opened a [PR](https://github.com/home-assistant/core/pull/62901) with HA and bdraco picked it up right away. He will eventually fold this integration into HA itself.
